FROM node:alpine

# Install dependencies
RUN apk add --no-cache python3 make g++ pkgconfig pixman pixman-dev cairo-dev pango-dev
RUN npm install -g @nestjs/cli

# Copy streaks sources
WORKDIR /transcendence
COPY package.json package.json
COPY package-lock.json package-lock.json

# Install npm dependencies
RUN npm i

# Expose port 3000
EXPOSE 3000

CMD [ "npm", "run", "start:dev" ]
